plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom' version '1.15-SNAPSHOT'
    id 'me.shedaniel.unified-publishing'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
}

loom {
    def aw = project(":common").file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("runs/client")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("runs/server")
        }
    }
}

unifiedPublishing {
    project {
        displayName = "[Fabric $minecraft_version_displayed] v${project.version}"
        releaseType = project.releaseType
        gameVersions = fabric_supported_mc_versions.split(", ?").toList()
        gameLoaders = [project.name, "quilt"]

        mainPublication jar

        var curseforgeToken = System.getenv("CURSEFORGE_TOKEN")
        var modrinthToken = System.getenv("MODRINTH_TOKEN")
        var changelogFile = rootProject.file("changelog.md").text

        if (curseforgeToken != null) {
            curseforge {
                token = curseforgeToken
                id = project.curse_project
                gameVersions.addAll "Java $java_version"
                changelog = changelogFile
            }
        }

        if (modrinthToken != null) {
            modrinth {
                token = modrinthToken
                id = project.modrinth_project
                version = "$minecraft_version_displayed-$project.version+$project.name"
                changelog = changelogFile.substring(changelogFile.indexOf('\n'), changelogFile.indexOf('\n\n'))
            }
        }
    }
}
