# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=6.1.0
group=net.themcbrothers.sharedadvancements
java_version=25

# Mod Properties
mod_name=Shared Advancements
mod_author=TheMCLoveMan
mod_id=sharedadvancements
license=MIT License
description=Share your advancements with your team or all players!

## https://projects.neoforged.net/neoforged/neoform
neoform_version=26.1-1

# Minecraft
minecraft_version=26.1
minecraft_version_range=[1.21.11,)
minecraft_version_displayed=26.1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_loader_version=0.18.4
fabric_supported_mc_versions=26.1

# Forge, see https://files.minecraftforge.net/net/minecraftforge/forge/ for new versions
forge_version=62.0.0
forge_loader_version_range=[52,)
forge_supported_mc_versions=26.1

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.0.1-beta
neoforge_loader_version_range=[4,)
neoforge_supported_mc_versions=26.1

# Publishing
github_repo=TheMCBrothers/Shared-Advancements
modrinth_project=78EIgPlj
curse_project=831959
releaseType=release

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
