# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=6.0.0-SNAPSHOT
group=net.themcbrothers.sharedadvancements
java_version=21

# Mod Properties
mod_name=Shared Advancements
mod_author=TheMCLoveMan
mod_id=sharedadvancements
license=MIT License
description=Share your advancements with your team or all players!

# Minecraft
minecraft_version=1.21.9
minecraft_version_range=[1.21,)
minecraft_version_displayed=1.21.X

# Fabric
fabric_loader_version=0.17.2
fabric_supported_mc_versions=1.21,1.21.1,1.21.2,1.21.3,1.21.4,1.21.5,1.21.6,1.21.7,1.21.8,1.21.9

# Forge
forge_version=59.0.0
forge_loader_version_range=[52,)
forge_supported_mc_versions=1.21.1,1.21.3,1.21.4,1.21.5,1.21.6,1.21.7,1.21.8,1.21.9

# NeoForge
neoforge_version=21.9.6-beta
neoforge_loader_version_range=[4,)
neoforge_supported_mc_versions=1.21,1.21.1,1.21.2,1.21.3,1.21.4,1.21.5,1.21.6,1.21.7,1.21.8,1.21.9

# Publishing
github_repo=TheMCBrothers/Shared-Advancements
modrinth_project=78EIgPlj
curse_project=831959
releaseType=release

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
