plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[7.0.11,8.0)'
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    runs {
        configureEach {
            args "-mixin.config=${mod_id}.mixins.json"
        }

        client {
            workingDir =  file('runs/client')
        }

        server {
            workingDir = file('runs/server')
            args '--nogui'
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:$minecraft_version-$forge_version")
}

unifiedPublishing {
    project {
        displayName = "[Forge $minecraft_version_displayed] v${project.version}"
        releaseType = project.releaseType
        gameVersions = forge_supported_mc_versions.split(", ?").toList()
        gameLoaders = [project.name]

        mainPublication jar

        var curseforgeToken = System.getenv("CURSEFORGE_TOKEN")
        var modrinthToken = System.getenv("MODRINTH_TOKEN")
        var changelogFile = rootProject.file("changelog.md").text

        if (curseforgeToken != null) {
            curseforge {
                token = curseforgeToken
                id = project.curse_project
                gameVersions.addAll "Java $java_version"
                changelog = changelogFile
            }
        }

        if (modrinthToken != null) {
            modrinth {
                token = modrinthToken
                id = project.modrinth_project
                version = "$minecraft_version_displayed-$project.version+$project.name"
                changelog = changelogFile.substring(changelogFile.indexOf('\n'), changelogFile.indexOf('\n\n'))
            }
        }
    }
}
