modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"
issueTrackerURL = "https://github.com/${github_repo}/issues"

[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    updateJSONURL = "https://neoforge.curseupdate.com/${curse_project}/${mod_id}"
    displayURL = "https://themcbrothers.net/mods"
    logoFile = "logo.png"
    logoBlur = false
    authors = "${mod_author}"
    description = '''${description}'''
    displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neoforge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[modproperties.${mod_id}]
    catalogueImageIcon = "icon.png"
