name: Java CI

on:
  push:
    branches-ignore:
      - '**-dev'
    paths:
      - '**.gradle'
      - '**.properties'
      - '**/src/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: TheMCBrothers/.github/.github/workflows/mod_ci.yml@main