name: Publish

on:
  push:
    branches-ignore:
      - '**-dev'
    paths:
      - '**.gradle'
      - '**.properties'
      - '**/src/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    uses: TheMCBrothers/.github/.github/workflows/mod_publish_unified.yml@main